version: '3.9'

services:
  prog-prod:
    build:
      context: .
      dockerfile: dockerfiles/prog.dockerfile
    volumes:
      - ./src:/src
    env_file:
      - src/.env-prod
    environment:
      TZ: Europe/Warsaw
    restart: on-failure


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.76.0/24
          gateway: 192.168.76.254
