version: '3.1'

services:
  db:
    image: mysql:8.0.34
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Europe/Warsaw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: ${DB_SERVER}
      PMA_PORTS: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      TZ: Europe/Warsaw

  memcached:
    image: memcached:1.6.22
    # restart: on-failure
    environment:
      TZ: Europe/Warsaw

  apache:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    depends_on:
      - db
      - memcached
    ports:
      - 8081:80
    volumes:
      - ./web/:/var/www/html/
    # restart: on-failure
    env_file:
      - src/.env
    environment:
      TZ: Europe/Warsaw

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: none
    ports:
      - 1025:1025 # smtp
      - 8025:8025 # web
    environment:
      TZ: Europe/Warsaw

  prog:
    build:
      context: .
      dockerfile: dockerfiles/prog-dev.dockerfile
    depends_on:
      - db
      - mailhog
    volumes:
      - ./src:/src
    # restart: on-failure
    env_file:
      - src/.env
    environment:
      TZ: Europe/Warsaw
    # stdin_open: true
    tty: true
    hostname: znb

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.75.0/24
          gateway: 192.168.75.254

volumes:
  mysql_data:
