"""dodanie tabeli ze szczegolami rozporzadzen

Revision ID: 2380ad82cc8b
Revises: 0bc96b40f8e3
Create Date: 2025-01-26 18:50:21.748619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2380ad82cc8b'
down_revision: Union[str, None] = '0bc96b40f8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rozporzadzenia', sa.Column('enriched', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rozporzadzenia', 'enriched')
    # ### end Alembic commands ###
