"""empty message

Revision ID: 8abc4fcbd2ae
Revises: 2380ad82cc8b
Create Date: 2025-01-26 18:51:33.326527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8abc4fcbd2ae'
down_revision: Union[str, None] = '2380ad82cc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('act_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('area', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['rozporzadzenia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details')
    # ### end Alembic commands ###
