"""czasy obowiazywania zakazow

Revision ID: b545d1723932
Revises: 8abc4fcbd2ae
Create Date: 2025-01-26 21:16:06.907366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b545d1723932'
down_revision: Union[str, None] = '8abc4fcbd2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_times',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('detail_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_times')
    # ### end Alembic commands ###
