"""podstawowy model danych v2

Revision ID: bbd176ac8f08
Revises: 
Create Date: 2023-11-20 21:22:22.936545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bbd176ac8f08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rozporzadzenia',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.String(length=16), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notif_started_proc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notif_finished_proc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statystyki',
    sa.Column('last_parse_du', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_update_db', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('last_parse_du')
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('confirmation', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_send', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('act_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['rozporzadzenia.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('users')
    op.drop_table('statystyki')
    op.drop_table('rozporzadzenia')
    # ### end Alembic commands ###
