"""model danych do obslugi notyfikacji sms

Revision ID: e3289475c940
Revises: b545d1723932
Create Date: 2025-06-08 07:47:32.866446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3289475c940'
down_revision: Union[str, None] = 'b545d1723932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_contacts',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('phone_number', sa.String(length=9), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(length=360), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('sms_notifications',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('soft_id', sa.String(length=32), nullable=True),
    sa.Column('date_send', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('act_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['rozporzadzenia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soft_id')
    )
    op.add_column('rozporzadzenia', sa.Column('notif_sms_cap', sa.Enum('non', 'alert', 'reminder', name='smsnotificationcapability'), server_default='NON', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rozporzadzenia', 'notif_sms_cap')
    op.drop_table('sms_notifications')
    op.drop_table('sms_contacts')
    # ### end Alembic commands ###
